EXECS=prefetch-print-trace prefetch-process-trace
CXXFLAGS=-g -O0

all: $(EXECS)

prefetch-print-trace: prefetch-print-trace.cpp

prefetch-process-trace: prefetch-process-trace.cpp

clean: 
	@rm -f $(EXECS)

