#!/bin/sh -e
# init script for stopping readahead profiling

# Check the package is still installed

# Get LSB functions
. /lib/lsb/init-functions
. /etc/default/rcS

PREFETCH_DIR=/.prefetch

stop_boot_trace() {
	sleep 60
    	echo "boot tracing stop" >/proc/prefetch
    	mkdir -p "$PREFETCH_DIR"
    	STAMP=`date +'%Y%m%d-%T'`
    	for file in /.prefetch-boot-trace.*; do
    		FILEBASENAME=$(basename "$file")
    		#copy latest trace
    		cp -af "$file" "$PREFETCH_DIR/$FILEBASENAME.$STAMP"
    		#take 3 latest traces
    		LAST_TRACES=$(ls -t1 "$PREFETCH_DIR/$FILEBASENAME".* | head -n 3)
    		#merge them and put as trace used at the next boot
    		/usr/sbin/prefetch-process-trace -c sort-sum $LAST_TRACES >"$file"
    	done
}

case "$1" in
    start)
    	stop_boot_trace &
	;;
    stop|restart|force-reload)
	;;
    *)
	echo "Usage: /etc/init.d/stop-readahead {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
